### ISSUE TITLE
Docker instructions on 2010 branch are broken

### ISSUE THREAD

**Issue by cbourjau** [cms-legacydata-analyses/HiForestProducerTool#25]
Following the instructions in the readme for the 2010 ( https://github.com/cms-opendata-analyses/HiForestProducerTool/tree/2010 ) branch I run into an error:
```shell
docker run --name opendata -it  gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_3_9_2_patch5-slc5_amd64_gcc434:2020-11-17-e0b0b7a6 /bin/bash

# NOTE: The url was also outdated (?)
git clone -b 2010 git://github.com/cms-opendata-analyses/HiForestProducerTool.git HiForestProducer
cd HiForestProducer/
scram b
# Doing the out-commenting
cmsRun hiforestanalyzer_cfg.py > full.log 2>&1 &

$ cat full.log 
210118 18:47:22 001 Xrd: XrdClientConn: Error resolving this host's domain name.
18-Jan-2021 19:36:15 CET  Initiating request to open file root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2010/HIAllPhysics/RECO/ZS-v2/0000/001DA267-7243-E011-B38F-001617C3B6CE.root
18-Jan-2021 19:36:17 CET  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2010/HIAllPhysics/RECO/ZS-v2/0000/001DA267-7243-E011-B38F-001617C3B6CE.root
%MSG-s CMSException:  AfterSourceConstruction 18-Jan-2021 19:36:20 CET  pre-events
cms::Exception caught in cmsRun
---- PluginNotFound BEGIN
Unable to find plugin 'TriggerInfoAnalyzer'. Please check spelling of name.
---- PluginNotFound END

```

**Comment by katilp** [comment]
Thanks for reporting! I I'll have a look.

**Comment by cbourjau** [comment]
You are welcome. No hurry, though. Unfortunately, it seems like the data is inaccessible for my use-case (running a 100% browser-based analysis) anyways. Vanilla ROOT access to the  data is a prerequisite.

**Comment by katilp** [comment]
I'm rerunning the test which is implemented in [the github workflow](https://github.com/cms-opendata-analyses/HiForestProducerTool/blob/2010/.github/workflows/main.yml) in this repository to check if the docker environment still works (it did at the time of the release). This test workflow can be run from the guthub web interface, but it is evidently not a solution for a full-scale analysis, being limited to 6h on github runners. Indeed, one of the areas we are working on is the usability of these data and how to improve that. For these old data, we do not have any validated reduced selection available (and the selection would also depend on the analysis one intends to do). Therefore, we have this example available, but admittedly, this is not an easy task to start with. For the moment, from the two options: 1) release what we have even though we know it is not easy to use or 2) do not release, we've chosen option 1) 🙂

**Comment by cbourjau** [comment]
Thanks for doing the work anyhow even if the academic world might not reward it adequately! I know this is not how it works but here is my thought anyways: The released data is inseparable from the CMSSW framework from ~2010. Its a hard dependency and without CMSSW the data could just as well be encrypted. For all intends and purposes, they are released as a package deal even if it is not explicitly stated anywhere. If no validated reduction exist than there is essentially no validated data. I know how hard it is to validate a data set and I know that probably nobody is going to see it through. However, in the current state the data will sadly be lost for future generations.

**Comment by katilp** [comment]
Well, we preserve what we have. For the moment, we rely on containers with CMSSW included, and they work. This is the first step. If there's interest and manpower in the future, these datasets can still be analyzed and reduced. Step by step. If we do not do this first step, these data are lost right now. Remember that these are very specific early HI data, different from the mainstream p-p. For p-p, for the Run1 data, we rely on CMSSW, but for the Run2, we will also have datasets independent from the CMSSW framework, which are validated (by their use in the collaboration), and released.

[The test workflow](https://github.com/cms-opendata-analyses/HiForestProducerTool/pull/26/checks?check_run_id=1723816398) went fine. Thanks for the correction in the git clone path, that's now implemented.

What puzzles me in what your reported that your job seems to have access to data:
```
18-Jan-2021 19:36:15 CET  Initiating request to open file root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2010/HIAllPhysics/RECO/ZS-v2/0000/001DA267-7243-E011-B38F-001617C3B6CE.root
18-Jan-2021 19:36:17 CET  Successfully opened file root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2010/HIAllPhysics/RECO/ZS-v2/0000/001DA267-7243-E011-B38F-001617C3B6CE.root
```
but then fails to find the sw module  `TriggerInfoAnalyzer`.

Was the compilation step (`scram b`) OK for you? It should end with 

```
@@@@ Checking shared library for missing symbols: libHiForestHiForestProducer.so
@@@@ ----> OK, shared library FULLY-BOUND (no missing symbols): libHiForestHiForestProducer.so
Leaving library rule at HiForest/HiForestProducer
@@@@ Running edmWriteConfigs for HiForestHiForestProducer
--- Registered EDM Plugin: HiForestHiForestProducer
>> Leaving Package HiForest/HiForestProducer
>> Package HiForest/HiForestProducer built
@@@@ Refreshing Plugins:EdmPluginRefresh
```

**Comment by cbourjau** [comment]
Here is the output I got:
```
[18:31:21] cmsusr@6a58614f13c3 ~/CMSSW_3_9_2_patch5/src/HiForestProducer $ scram b
Reading cached build data
>> Local Products Rules ..... started
>> Local Products Rules ..... done
>> Entering Package HiForestProducer/src
>> Leaving Package HiForestProducer/src
>> Package HiForestProducer/src built
>> Entering Package HiForestProducer/python
>> Leaving Package HiForestProducer/python
>> Package HiForestProducer/python built
>> Subsystem HiForestProducer built
```

Anyhow, I'm afraid I won't be able to be of much further assistance. Thanks again.

**Comment by katilp** [comment]
Thanks a lot, that looks OK. Now I also see the problem, we are actually lacking one directory level in the instructions. 

As mentioned in
http://opendata.cern.ch/docs/cms-guide-troubleshooting
the exception `PluginNotFound` comes because of the directory structure. I have now updated the instructions accordingly.

Many thanks for you feedback!
